### ISSUE TITLE
Catch up with stable version

### ISSUE THREAD

**Issue by weihanglo** [rust-tw/book-tw#114]
The stable version is now under 1.62.0. Maybe we can choose a commit and catch up with  it 
https://doc.rust-lang.org/stable/book/

**Comment by wusyong** [comment]
I can take this but probably next month. Do you know if the book has published physical copies of 2021 edition?

**Comment by weihanglo** [comment]
No I wasn't aware of any news.

Perhaps we can seek help from the Taiwan community?

**Comment by wusyong** [comment]
I just need to know what's the version of physical books. So we could update to that one at least.

**Comment by weihanglo** [comment]
I think this has been resolved. Thank you @wusyong and @CYBAI for your fantastic works!
