### ISSUE TITLE
有關 reference 的翻譯

### ISSUE THREAD

**Issue by chengr4** [rust-tw/book-tw#150]
你好：

有關段落 [13.1 - 獲取引用或移動所有權](https://rust-lang.tw/book-tw/ch13-01-closures.html#%E7%8D%B2%E5%8F%96%E5%BC%95%E7%94%A8%E6%88%96%E7%A7%BB%E5%8B%95%E6%89%80%E6%9C%89%E6%AC%8A) 

「閉包要從它們周圍環境取得數值有三種方式，這能直接對應於函式取得參數的三種方式：不可變借用、可變借用，與取得所有權。閉包會依照函式本體如何使用獲取的數值，來決定要用哪種方式。在範例 13-4 中，我們定義一個閉包來獲取 list 向量的不可變引用，因為它只需要不可變引用就能印出數值：」

其中，單字「不可變借用」和後面的「不可變引用」讓我第一時間產生混亂，跑去原文發現是 *borrowing immutably* 以及 *immutable reference*

然後看了一下[中英術語對照表](https://rust-lang.tw/book-tw/appendix-08-terminology.html)，裡面 reference 是翻作 「參照或參考」，想冒昧請問一下這是否是需要修改的部分？

例外在翻譯後面用小括號備注原文是否能增加使用者體驗？

例如：這能直接對應於函式取得參數的三種方式：不可變借用(borrowing immutably)、可變借用(borrowing mutably)，與取得所有權(taking ownership)

**Comment by wusyong** [comment]
我想這是我的錯誤了，我當時在對照表的確是用參考，但在大部份的章節我卻都用引用。
@weihanglo 如果你同意的話我可以把所有 reference 改成參考。
這將包括「參考」、「解參考」、「參考計數」、「強/弱參考」。

@chengr4 如果翻譯後仍不易理解的話歡迎在該文章第一次出現時在後面加上括號備註原文

**Comment by weihanglo** [comment]
您好：

我們的確在其他地方有加括號，不過為了避免括號太多過於混亂，通常只在書中第一次提及時使用。reference 和 borrow 的翻譯在此 https://rust-lang.tw/book-tw/ch04-02-references-and-borrowing.html

**Comment by weihanglo** [comment]
> @weihanglo 如果你同意的話我可以把所有 reference 改成參考。
> 這將包括「參考」、「解參考」、「參考計數」、「強/弱參考」。


我覺得可以，只要確認這個是通用的詞彙就行。

**Comment by wusyong** [comment]
國家雙語兩者都有，但參考比較多。
我最近有買了 Rust 程式設計那本也是用參考，所以我願意統一翻譯。
我之後會發PR修改並確定引用都改成參考

**Comment by chengr4** [comment]
非常感謝兩位大大，如果改成參考，以這個 case 來說，就不會混亂也不用特別加註小括號了，之後如果有機會能看到需要加小括號的 case 會再開 issue 或者 PR 詢問。

再次感謝兩位大大
