### ISSUE TITLE
有關 explicitly 的翻譯

### ISSUE THREAD

**Issue by chengr4** [rust-tw/book-tw#157]
你好：

目前我正在閱讀 [4.1 記憶體與分配](https://rust-lang.tw/book-tw/ch04-01-what-is-ownership.html#%E8%A8%98%E6%86%B6%E9%AB%94%E8%88%87%E5%88%86%E9%85%8D)

讀至「沒有 GC 的話，識別哪些記憶體不再使用並顯式呼叫程式碼釋放它們就是我們的責任了，就像我們請求取得它一樣。」

我覺得用「明確地呼叫程式」或者「明確的呼叫程式」比「顯式呼叫程式」更加直觀。

還是 explicitly 被翻作 「顯式」已經是一個傳統了？

想請有時間的大大，可以幫小弟解惑，非常感謝 🙏

**Comment by wusyong** [comment]
顯性/顯式是國家教育研究院樂詞網的詞彙
不過我們並不反對翻譯的更順暢，如果你覺得可以的話歡迎協助修改

**Comment by CYBAI** [comment]
Fixed by #159
