### ISSUE TITLE
Builder Pattern 的翻譯

### ISSUE THREAD

**Issue by hms5232** [rust-tw/book-tw#166]
在開始討論詞彙翻譯之前，我想先問大家，「generate」會怎麼翻譯呢？

答案有可能是「產生」或「生成」兩種吧，前者是台灣正統用法，後者是中國那邊的翻譯。關於這點我有做了一個 commit https://github.com/hms5232/book-tw/commit/fc23462cb7b31b7ef30b3fd7470a95ab8989cc72 要修正，之後會發 PR。

------

回到標題，關於 Builder Pattern 的 Pattern，翻譯成「設計模式」或「模式」相信大家應該都能接受，但是在 Builder 的翻譯就比較微妙。

目前 Builder Pattern 只有出現在附錄 8 中，翻譯成「生成器模式」參考來源是維基百科。首先我看到的第一個點，翻譯和 generate 重複，第二點是該維基百科條目並沒有繁簡轉換（不過第一句話倒是有提到「建造模式」）：

![圖片](https://github.com/rust-tw/book-tw/assets/43672033/29822b07-5c16-4d27-85c7-6b84fe73f9d5)

------

這邊講個題外話，有繁簡轉換公共轉換組也不一定會是正確的，例如：

![圖片](https://github.com/rust-tw/book-tw/assets/43672033/f9c9c572-eb2a-44c5-a200-1e122f632984)

很明顯，台灣沒有「編程」這種用語，都是講「程式設計」。

維基百科的標題可以獨立設定轉換，但明顯的上圖雖然有套用資訊公共轉換，卻沒有另外對條目標題轉換。

一個比較好的條目大概是這樣：

![圖片](https://github.com/rust-tw/book-tw/assets/43672033/8a819429-ab24-454b-9fc6-371fab8c760e)

有套用公共轉換、有針對各地區改善標題在地化。

------

扯有點多了，總之 Builder Pattern 參考對象翻譯並不準確（至少不符合台灣原生術語），故想提出討論希望改成一個較為準確且符合台灣原生用法的翻譯。

直接 google 後，目前比較可以見到的翻譯是「建造者模式」。

個人之前在 Laravel 上看到「Query builder」的社群翻譯是「[查詢產生器](https://laravel.tw/docs/5.0/queries)」或「[查詢建構器](https://laravel.tw/docs/5.2/queries)」，感覺也滿能表達意思的。

所以針對 Builder Pattern 的翻譯，目前我比較推薦改成下列之一：

* 建造者模式
* 建構器模式
* 產生器模式

想聽聽大家的看法。

最後，目前我正在利用空閒時間學習 Rust，感謝大家的熱心，讓我在學習的時候有如此棒的資源可以入門。在閱讀過程中，也有發現一些可以改善的小地方，預計接下來這一周到一個段落會發出 PR（如一開始提到的 generate），再麻煩大家協助審閱了。

**Comment by weihanglo** [comment]
感謝提供想法！社群翻譯雖已認真校稿但百密一疏，需要諸位火眼金睛協助糾錯，非常歡迎提交 pull request！

**Comment by hms5232** [comment]
> 感謝提供想法！社群翻譯雖已認真校稿但百密一疏，需要諸位火眼金睛協助糾錯，非常歡迎提交 pull request！

套句學生時代老師常講的話：我只是在測試你們有沒有認真上課(X

目前就我的理解，那三個詞套用這個設計模式，都能表現出該模式的精神（如果我的理解無誤的話啦）；而搜尋下來，應該是「建造者模式」最多人使用，如果沒有其他想法，我就會跟著這次念書段落的 PR 一起發出哩。

**Comment by hms5232** [comment]
Close issue because PR was merged 🎉
