### ISSUE TITLE
Interest in translating Comprehensive Rust 🦀?

### ISSUE THREAD

**Issue by mgeisler** [rust-tw/book-tw#168]
Dear all,

I work in Android and we've written a course called [Comprehensive Rust 🦀](https://google.github.io/comprehensive-rust/). It was recently on the front-page of [Hackernews](https://news.ycombinator.com/item?id=36048261#36053059).

The course is being translated into other languages: a [Chinese (Traditional)](https://github.com/google/comprehensive-rust/issues/684) translation is just starting.

If someone here would like to help, then please come talk to us in the issue! I proposed some steps to help [organize the translations](https://github.com/google/comprehensive-rust/issues/684#issuecomment-1562633027). Thanks for your time!

**Comment by weihanglo** [comment]
Glad to see the Traditional Chinese version is up now. Thank you for working on translation for Rust community :)
