### ISSUE TITLE
章節審核：Ch 16.2, CH 17.3

### ISSUE THREAD

**Issue by z-Wind** [rust-tw/book-tw#50]
## 此章節的文章：

- [ ] ch 16-02

- 有錯別字
> 當執行範例 16-10 的程式碼，你應該會看到以下輸出，每一行會**間格**一秒鐘

間格  => 間隔

>讓我們來使用 mpsc 並**擴產**範例 16-10

擴產 => 擴展

## 此章節的文章：

- [ ] ch 17-03

- 有錯別字
> 這代表我們之後**可意**實作個方法來控制 content 欄位資料該怎麼讀取

可意  => 可以

**Comment by weihanglo** [comment]
感謝！也歡迎發送 PR！

**Comment by z-Wind** [comment]
已發送 PR，不過這是我第一次發送，不知道有沒有問題，麻煩你了

**Comment by weihanglo** [comment]
Fixed #51 

Highly thank for your contribution!
