### ISSUE TITLE
Change term "生命週期" to “生命期“ or else

### ISSUE THREAD

**Issue by weihanglo** [rust-tw/book-tw#56]
I feel a bit astray about the translation of the term "lifetime", which means from birth to death of a resource. However, currently we choose 生命週期, which implies "cycle" for the word "週“, and the directly translation of 生命週期 to English is "lifecycle" but not "lifetime". I propose to change the translation to "生命期" or other better alternative. Thanks.

**Comment by weihanglo** [comment]
cc @wusyong @CYBAI  you might be interested in this

**Comment by CYBAI** [comment]
Indeed, I agree with you that 生命週期 should be equal to "lifecycle". 
Just searched [`lifetime` on `國家教育研究院雙語詞彙、學術名詞暨辭書資訊網`](https://terms.naer.edu.tw/search/?q=%22lifetime%22&q=&field=ti&field=ti&op=AND&op=AND&match=&order=&num=50&show=&page=&group=&heading=#result); it seems it can be translated as `壽命` as well but `生命期` is also good for me 👀 

Maybe I will vote for `生命期` for the translation in rust.

**Comment by wusyong** [comment]
No preference for this frome me. If `生命期` is more preferred, we could update it right away.

**Comment by weihanglo** [comment]
We did a simple poll in the community and the result lead us to keep the term "生命週期“. Close now. Thanks!
