### ISSUE TITLE
CONTRIBUTING.md => 翻譯流程 => open pull requests 的超連結失效 

### ISSUE THREAD

**Issue by fkztw** [rust-tw/book-tw#62]
如題 
https://github.com/rust-tw/book-tw/blob/zh_tw/CONTRIBUTING.md#%E7%BF%BB%E8%AD%AF%E6%B5%81%E7%A8%8B

https://github.com/rust-lang.tw/rfcs/pulls 失效

**Comment by CYBAI** [comment]
Fixed by https://github.com/rust-tw/book-tw/pull/102
